export const HttpStatus = {
  100: { code: 100, name: "Continue", category: "Informational" },
  101: { code: 101, name: "SwitchingProtocols", category: "Informational" },
  102: { code: 102, name: "Processing", category: "Informational" },
  103: { code: 103, name: "EarlyHints", category: "Informational" },

  200: { code: 200, name: "OK", category: "Success" },
  201: { code: 201, name: "Created", category: "Success" },
  202: { code: 202, name: "Accepted", category: "Success" },
  203: { code: 203, name: "NonAuthoritativeInformation", category: "Success" },
  204: { code: 204, name: "NoContent", category: "Success" },
  205: { code: 205, name: "ResetContent", category: "Success" },
  206: { code: 206, name: "PartialContent", category: "Success" },
  207: { code: 207, name: "MultiStatus", category: "Success" },
  208: { code: 208, name: "AlreadyReported", category: "Success" },
  226: { code: 226, name: "IMUsed", category: "Success" },

  300: { code: 300, name: "MultipleChoices", category: "Redirection" },
  301: { code: 301, name: "MovedPermanently", category: "Redirection" },
  302: { code: 302, name: "Found", category: "Redirection" },
  303: { code: 303, name: "SeeOther", category: "Redirection" },
  304: { code: 304, name: "NotModified", category: "Redirection" },
  305: { code: 305, name: "UseProxy", category: "Redirection" },
  307: { code: 307, name: "TemporaryRedirect", category: "Redirection" },
  308: { code: 308, name: "PermanentRedirect", category: "Redirection" },

  400: { code: 400, name: "BadRequest", category: "Client Error" },
  401: { code: 401, name: "Unauthorized", category: "Client Error" },
  402: { code: 402, name: "PaymentRequired", category: "Client Error" },
  403: { code: 403, name: "Forbidden", category: "Client Error" },
  404: { code: 404, name: "NotFound", category: "Client Error" },
  405: { code: 405, name: "MethodNotAllowed", category: "Client Error" },
  406: { code: 406, name: "NotAcceptable", category: "Client Error" },
  407: {
    code: 407,
    name: "ProxyAuthenticationRequired",
    category: "Client Error",
  },
  408: { code: 408, name: "RequestTimeout", category: "Client Error" },
  409: { code: 409, name: "Conflict", category: "Client Error" },
  410: { code: 410, name: "Gone", category: "Client Error" },
  411: { code: 411, name: "LengthRequired", category: "Client Error" },
  412: { code: 412, name: "PreconditionFailed", category: "Client Error" },
  413: { code: 413, name: "PayloadTooLarge", category: "Client Error" },
  414: { code: 414, name: "URITooLong", category: "Client Error" },
  415: { code: 415, name: "UnsupportedMediaType", category: "Client Error" },
  416: { code: 416, name: "RangeNotSatisfiable", category: "Client Error" },
  417: { code: 417, name: "ExpectationFailed", category: "Client Error" },
  418: { code: 418, name: "ImATeapot", category: "Client Error" },
  421: { code: 421, name: "MisdirectedRequest", category: "Client Error" },
  422: { code: 422, name: "UnprocessableEntity", category: "Client Error" },
  423: { code: 423, name: "Locked", category: "Client Error" },
  424: { code: 424, name: "FailedDependency", category: "Client Error" },
  425: { code: 425, name: "TooEarly", category: "Client Error" },
  426: { code: 426, name: "UpgradeRequired", category: "Client Error" },
  428: { code: 428, name: "PreconditionRequired", category: "Client Error" },
  429: { code: 429, name: "TooManyRequests", category: "Client Error" },
  431: {
    code: 431,
    name: "RequestHeaderFieldsTooLarge",
    category: "Client Error",
  },
  451: {
    code: 451,
    name: "UnavailableForLegalReasons",
    category: "Client Error",
  },

  500: { code: 500, name: "InternalServerError", category: "Server Error" },
  501: { code: 501, name: "NotImplemented", category: "Server Error" },
  502: { code: 502, name: "BadGateway", category: "Server Error" },
  503: { code: 503, name: "ServiceUnavailable", category: "Server Error" },
  504: { code: 504, name: "GatewayTimeout", category: "Server Error" },
  505: { code: 505, name: "HTTPVersionNotSupported", category: "Server Error" },
  506: { code: 506, name: "VariantAlsoNegotiates", category: "Server Error" },
  507: { code: 507, name: "InsufficientStorage", category: "Server Error" },
  508: { code: 508, name: "LoopDetected", category: "Server Error" },
  510: { code: 510, name: "NotExtended", category: "Server Error" },
  511: {
    code: 511,
    name: "NetworkAuthenticationRequired",
    category: "Server Error",
  },
} as const;
